language: python

python:
  - "3.6"

jobs:
  include:
    - stage: test build
      before_install: pip install pipenv
      install: pipenv install --dev
      script:
        - pipenv-setup check
        - pipenv run python3 setup.py sdist bdist_wheel
    - stage: deploy
      if: branch = master AND type != pull_request
      before_install:
        - pip install pipenv
        - sudo apt-get update
        - sudo apt-get install expect
        - openssl aes-256-cbc -K $encrypted_415b34294001_key -iv $encrypted_415b34294001_iv -in nise-travis-ci.enc -out ${TRAVIS_HOME}/deploy_key.pem -d
      install: pipenv install --dev
      before_script:
        - eval "$(ssh-agent -s)"
        - chmod 600 ${TRAVIS_HOME}/deploy_key.pem
        - >
          expect -c "
            spawn ssh-add ${TRAVIS_HOME}/deploy_key.pem
            expect \"?assphrase\"
            send \"\r\"
            expect eof"
        - ssh-add -l
        - git remote add deploy git@github.com:project-koku/nise.git
        - git fetch deploy
      script:
        - export SEMVER=$(python setup.py --version)
        - pipenv-setup check
        - pipenv run python3 setup.py sdist bdist_wheel
        - >
          if [ ! -z $(git tag -l "${SEMVER}") ]; then
            echo "Tag already exists, doing nothing";
          else
            echo "Creating tag ${SEMVER}";
            git tag ${SEMVER};
            git push deploy --tags;
            pipenv run python3 -m twine upload dist/*
          fi
