sudo: false

language: python

python:
  - "3.6"

env:
  TOXENV=for_travis
  CC_TEST_REPORTER_ID=45a9f7a2e55a514bd037ad818a163cf97cec0a50a743602e790d4584909aebe3

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - pip install tox

script:
  - tox

after_success:
  - ./cc-test-reporter after-build
