start_date: '2019-11-01'
end_date: '2020-01-31'
storage_classes:
- gp2
name_wordiness: 2
max_resource_id_length: 10
max_nodes: 100
max_node_cpu_cores: 100
max_node_memory_gig: 256
max_node_namespaces: 10
max_node_namespace_pods: 100
min_node_namespace_pod_seconds: 300
max_node_namespace_pod_seconds: 3600
max_node_namespace_pod_labels: 5
max_node_namespace_volumes: 100
max_node_namespace_volume_labels: 3
max_node_namespace_volume_request_gig: 256
max_node_namespace_volume_volume_claims: 100
max_node_namespace_volume_volume_claim_capacity_gig: 256
max_node_namespace_volume_volume_claim_labels: 2
