name: Publish

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish koku-nise to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          VERSION=$(python setup.py --version)
          if [ ! -z $(git tag -l "${VERSION}") ]; then
            echo "Tag already exists, doing nothing";
          else
            echo "Creating tag ${VERSION}";
            git tag ${VERSION};
            git push deploy --tags;
            python3 setup.py sdist bdist_wheel
            python3 -m twine upload dist/*
          fi
